server:
  port: 8099

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: books
          uri: http://localhost:8090
          predicates:
            - Path=/api/books/**
          filters:
            - RewritePath=/api/books/(?<segment>.*), /book/${segment}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE