server:
  port: 8092

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # Development only
    properties:
      hibernate:
        format_sql: true # Development only
        transaction.coordinator_class: jdbc
    defer-datasource-initialization: true
  sql:
    init:
      mode: never # always only for Initialization
      schema-locations: optional:classpath*:v1.0-init-user.sql

jwt:
  secret:
    key: GbEjhArbMxCF6@NA,2&41K5w_Bu9N#7a_b0}VD(2u4]Y/)2U2M=jc8WXS+0
  expiration-hour: 24
  issuer: http://localhost:8092
  public:
    key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiF00+foIUuFyO5FbqjMvwc++oQvyH0wviN6+7ev9ARc33rwa3doHBX40OyQ4KJPZu0O+z0SY88OUZJsMWk8mSdQlN0/JdyIA7FDuORiQEgQ6mDPh8LLkgXJ97ZUxvZDC/FjchhCI9FqeSOHCEU+F8TKotufT9DO6Mw1mm0sfG+nkmA2z8rJNOIiGw4uGUWYD/ABa+av/pauvCkOUsEZE4TWmyaZdM6p//p4bdD545C7AQSrdt7c4f1j/0SDorDAicENrQNAu1lThjdD4ES93rxVALR14Tqfxn4AChkrpKmuUsfzzD+3KH9VJuKvTUa1ko3HtU5ewgs5e5mFvhKezXwIDAQAB
      -----END PUBLIC KEY-----

  private:
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCIXTT5+ghS4XI7kVuqMy/Bz76hC/IfTC+I3r7t6/0BFzfevBrd2gcFfjQ7JDgok9m7Q77PRJjzw5RkmwxaTyZJ1CU3T8l3IgDsUO45GJASBDqYM+HwsuSBcn3tlTG9kML8WNyGEIj0Wp5I4cIRT4XxMqi259P0M7ozDWabSx8b6eSYDbPysk04iIbDi4ZRZgP8AFr5q/+lq68KQ5SwRkThNabJpl0zqn/+nht0PnjkLsBBKt23tzh/WP/RIOisMCJwQ2tA0C7WVOGN0PgRL3evFUAtHXhOp/GfgAKGSukqa5Sx/PMP7cof1Um4q9NRrWSjce1Tl7CCzl7mYW+Ep7NfAgMBAAECggEAAo5rN6E44qXK6cVYUjhf+BYyGU/I5v+u+Ocnd63Pvm1MWLbHVWNwJUJBJC2b/UmERDZm8dFgWguoJLFKon2xlrYISVduOGOg/aW8cOlWxrBNh4PpKw8rKWHrHgq6E3vxNQzWyraZ8qkzJqjZZdo3cYz7EYxB3tJHbL0yiOD4I5iaOgkck1p91PXD+2dRi5Jl/PEf+pMveUFYJJUUcAJpE/7LlO/BsYVaN5jjOuBjBF2TW9nz3PCBCiN9i7LHbr18PDsk0o4bBacSs+QYEgwlGse/4m9l7mCIcgNgQGQk65lm6yUOnrA5tQaTe0Q4g7CNgUH/BAsYV1wbC+66YOFAHQKBgQC888FnkXr+s0oSvrL1mDCUBBpQYGC8zOosqdiHX40bUA+Vt1Fx1E1Yms9Yl1P4cdJvzwI+3PDLeXOj1WX4TIviTTR92r8QXWBJZmRTBrwlJxyf6OrpT6bA8NK3Od1HiB5t85c6fGdUpjQvpOQEJxF1Lf7ZJGiCFnUdSVqNlsvQtQKBgQC4wGXREkT7A4lh+cF0bo87nMC0ES1n5J1pALB3r60RDg/BQdmXu9rngrR0SsR0w/NeX7meQo478BtcdPd1o5RnRg7LxPiMFgX/27MlcrgqVs9ZqYb18jzD5RtnOICf2ihm9dx4L79n82c+zKbYFsacZfMfPFxXf28Gy/MHzmBEQwKBgQCEaq7XTfTMGgmHKW1w/77LfDSUr3Yb2d8ifcTo2eWhhnHlkhrZktbBiXxVsXd/XQUEpiYEuAFoFy0bW6miYMKHTWPD71CGv2mDBua36LhhsQ82YZx+9Pr/q8V/8mVIg/QPSe5pZlVj1TYtTXkeD+MEI7+9nO5AfEyGwalcIJmlIQKBgHeus4aP1j3h2aKtn8PkR0dv0WoU4pw1/j7iYm72UCAHQu+H0AS6fiGRi4L2WHPn6IVPb7h1Fxz++0qWvyPnFyEbwkQA0p41Oie4VEJDIcjTubk02CgFh5XDmk/wy2pCcf/Y77yv+cfGZzDIdKDxiDIS3T9z48IO3IbDoimBaN1vAoGAYXLX/5Nl0fh0E1OEJo4aY9mG6/VdmVG8tvK7XJSUIkoCueGtfnXv8wSdvpMMxoCg1dTPEFlLzRzS2WOzLdWM7e3Xq4y5zdiemoc2dqeF79pHHcv4Pneb/sjtKmWuT6IYL1xeDOeAgRSQMKmtDTLy8HyaSYsasMaLdDsiOJYtRyA=
      -----END PRIVATE KEY-----

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web.filter.OncePerRequestFilter: DEBUG
